plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      type: posts
    values:
      author: 방성범 (Bang Seongbeom)

permalink: /:title:output_ext

lang: ko
title: 방성범 블로그
author: 방성범 (Bang Seongbeom)
email: bangseongbeom@hotmail.com
description: 개발자 방성범의 기술 블로그

disqus:
  shortname: bangseongbeom

github_username: bangseongbeom
rss: rss

google_analytics: UA-125900715-1

show_excerpts: true

list_title: 글 목록

minima:
  date_format: "%F"

theme: minima
