plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title:output_ext

title: 방성범
author: 방성범 (Bang Seongbeom)
email: bangseongbeom@hotmail.com
description: 방성범의 블로그

disqus:
  shortname: bangseongbeom

github_username: bangseongbeom
rss: rss

google_analytics: UA-125900715-1

show_excerpts: true

minima:
  date_format: "%F"

theme: minima
